name: Deploy to EC2

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          HOST="${{ secrets.EC2_HOST }}"
          HOST_DOMAIN=$(echo "$HOST" | cut -d@ -f2)
          ssh-keyscan -H "$HOST_DOMAIN" >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
        run: |
           ssh -T -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa "$EC2_HOST" "
           set -e
           cd ~/automl-cicd-pipeline
           git pull origin main
           docker build -t automl-api .
           docker stop automl-api || true
           docker run --rm -d --name automl-api -p 8000:8000 automl-api
           "