name: Deploy to EC2

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $(echo ${{ secrets.EC2_HOST }} | cut -d@ -f2) >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
        run: |
            ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.EC2_HOST }} << 'EOF'
              set -e  # Stop on any error
              cd ~/automl-cicd-pipeline
              git pull origin main
              docker build -t automl-api .
              docker stop automl-api || true
              docker rm automl-api || true
              docker run -d --name automl-api -p 8000:8000 automl-api
            EOF